#Modified by Yeuk Ting Chu (Rovenna) - ytc17

import sys
assert sys.version_info >= (3, 5) # make sure we have Python 3.5+
from pyspark.sql import SparkSession, functions, types



benefits_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('StandardComponentId', types.StringType()),
types.StructField('PlanId', types.StringType()),
types.StructField('BenefitName', types.StringType()),
types.StructField('CopayInnTier1', types.StringType()),
types.StructField('CopayInnTier2', types.StringType()),
types.StructField('CopayOutofNet', types.StringType()),
types.StructField('CoinsInnTier1', types.StringType()),
types.StructField('CoinsInnTier2', types.StringType()),
types.StructField('CoinsOutofNet', types.StringType()),
types.StructField('IsEHB', types.StringType()),
types.StructField('IsCovered', types.StringType()),
types.StructField('QuantLimitOnSvc', types.StringType()),
types.StructField('LimitQty', types.StringType()),
types.StructField('LimitUnit', types.StringType()),
types.StructField('Exclusions', types.StringType()),
types.StructField('Explanation', types.StringType()),
types.StructField('EHBVarReason', types.StringType()),
types.StructField('IsExclFromInnMOOP', types.StringType()),
types.StructField('IsExclFromOonMOOP', types.StringType()),
])



plan_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('MarketCoverage', types.StringType()),
types.StructField('DentalOnlyPlan', types.StringType()),
types.StructField('TIN', types.StringType()),
types.StructField('StandardComponentId', types.StringType()),
types.StructField('PlanMarketingName', types.StringType()),
types.StructField('HIOSProductId', types.StringType()),
types.StructField('HPID', types.StringType()),
types.StructField('NetworkId', types.StringType()),
types.StructField('ServiceAreaId', types.StringType()),
types.StructField('FormularyId', types.StringType()),
types.StructField('IsNewPlan', types.StringType()),
types.StructField('PlanType', types.StringType()),
types.StructField('MetalLevel', types.StringType()),
types.StructField('DesignType', types.StringType()),
types.StructField('UniquePlanDesign', types.StringType()),
types.StructField('QHPNonQHPTypeId', types.StringType()),
types.StructField('IsNoticeRequiredForPregnancy', types.StringType()),
types.StructField('IsReferralRequiredForSpecialist', types.StringType()),
types.StructField('SpecialistRequiringReferral', types.StringType()),
types.StructField('PlanLevelExclusions', types.StringType()),
types.StructField('IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee', types.StringType()),
types.StructField('CompositeRatingOffered', types.StringType()),
types.StructField('ChildOnlyOffering', types.StringType()),
types.StructField('ChildOnlyPlanId', types.StringType()),
types.StructField('WellnessProgramOffered', types.StringType()),
types.StructField('DiseaseManagementProgramsOffered', types.StringType()),
types.StructField('EHBPercentTotalPremium', types.StringType()),
types.StructField('EHBPediatricDentalApportionmentQuantity', types.StringType()),
types.StructField('IsGuaranteedRate', types.StringType()),
types.StructField('PlanEffectiveDate', types.StringType()),
types.StructField('PlanExpirationDate', types.StringType()),
types.StructField('OutOfCountryCoverage', types.StringType()),
types.StructField('OutOfCountryCoverageDescription', types.StringType()),
types.StructField('OutOfServiceAreaCoverage', types.StringType()),
types.StructField('OutOfServiceAreaCoverageDescription', types.StringType()),
types.StructField('NationalNetwork', types.StringType()),
types.StructField('URLForEnrollmentPayment', types.StringType()),
types.StructField('FormularyURL', types.StringType()),
types.StructField('PlanId', types.StringType()),
types.StructField('PlanVariantMarketingName', types.StringType()),
types.StructField('CSRVariationType', types.StringType()),
types.StructField('IssuerActuarialValue', types.StringType()),
types.StructField('AVCalculatorOutputNumber', types.StringType()),
types.StructField('MedicalDrugDeductiblesIntegrated', types.StringType()),
types.StructField('MedicalDrugMaximumOutofPocketIntegrated', types.StringType()),
types.StructField('MultipleInNetworkTiers', types.StringType()),
types.StructField('FirstTierUtilization', types.StringType()),
types.StructField('SecondTierUtilization', types.StringType()),
types.StructField('SBCHavingaBabyDeductible', types.StringType()),
types.StructField('SBCHavingaBabyCopayment', types.StringType()),
types.StructField('SBCHavingaBabyCoinsurance', types.StringType()),
types.StructField('SBCHavingaBabyLimit', types.StringType()),
types.StructField('SBCHavingDiabetesDeductible', types.StringType()),
types.StructField('SBCHavingDiabetesCopayment', types.StringType()),
types.StructField('SBCHavingDiabetesCoinsurance', types.StringType()),
types.StructField('SBCHavingDiabetesLimit', types.StringType()),
types.StructField('SBCHavingSimplefractureDeductible', types.StringType()),
types.StructField('SBCHavingSimplefractureCopayment', types.StringType()),
types.StructField('SBCHavingSimplefractureCoinsurance', types.StringType()),
types.StructField('SBCHavingSimplefractureLimit', types.StringType()),
types.StructField('SpecialtyDrugMaximumCoinsurance', types.StringType()),
types.StructField('InpatientCopaymentMaximumDays', types.StringType()),
types.StructField('BeginPrimaryCareCostSharingAfterNumberOfVisits', types.StringType()),
types.StructField('BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays', types.StringType()),
types.StructField('MEHBInnTier1IndividualMOOP', types.StringType()),
types.StructField('MEHBInnTier1FamilyPerPersonMOOP', types.StringType()),
types.StructField('MEHBInnTier1FamilyPerGroupMOOP', types.StringType()),
types.StructField('MEHBInnTier2IndividualMOOP', types.StringType()),
types.StructField('MEHBInnTier2FamilyPerPersonMOOP', types.StringType()),
types.StructField('MEHBInnTier2FamilyPerGroupMOOP', types.StringType()),
types.StructField('MEHBOutOfNetIndividualMOOP', types.StringType()),
types.StructField('MEHBOutOfNetFamilyPerPersonMOOP', types.StringType()),
types.StructField('MEHBOutOfNetFamilyPerGroupMOOP', types.StringType()),
types.StructField('MEHBCombInnOonIndividualMOOP', types.StringType()),
types.StructField('MEHBCombInnOonFamilyPerPersonMOOP', types.StringType()),
types.StructField('MEHBCombInnOonFamilyPerGroupMOOP', types.StringType()),
types.StructField('DEHBInnTier1IndividualMOOP', types.StringType()),
types.StructField('DEHBInnTier1FamilyPerPersonMOOP', types.StringType()),
types.StructField('DEHBInnTier1FamilyPerGroupMOOP', types.StringType()),
types.StructField('DEHBInnTier2IndividualMOOP', types.StringType()),
types.StructField('DEHBInnTier2FamilyPerPersonMOOP', types.StringType()),
types.StructField('DEHBInnTier2FamilyPerGroupMOOP', types.StringType()),
types.StructField('DEHBOutOfNetIndividualMOOP', types.StringType()),
types.StructField('DEHBOutOfNetFamilyPerPersonMOOP', types.StringType()),
types.StructField('DEHBOutOfNetFamilyPerGroupMOOP', types.StringType()),
types.StructField('DEHBCombInnOonIndividualMOOP', types.StringType()),
types.StructField('DEHBCombInnOonFamilyPerPersonMOOP', types.StringType()),
types.StructField('DEHBCombInnOonFamilyPerGroupMOOP', types.StringType()),
types.StructField('TEHBInnTier1IndividualMOOP', types.StringType()),
types.StructField('TEHBInnTier1FamilyPerPersonMOOP', types.StringType()),
types.StructField('TEHBInnTier1FamilyPerGroupMOOP', types.StringType()),
types.StructField('TEHBInnTier2IndividualMOOP', types.StringType()),
types.StructField('TEHBInnTier2FamilyPerPersonMOOP', types.StringType()),
types.StructField('TEHBInnTier2FamilyPerGroupMOOP', types.StringType()),
types.StructField('TEHBOutOfNetIndividualMOOP', types.StringType()),
types.StructField('TEHBOutOfNetFamilyPerPersonMOOP', types.StringType()),
types.StructField('TEHBOutOfNetFamilyPerGroupMOOP', types.StringType()),
types.StructField('TEHBCombInnOonIndividualMOOP', types.StringType()),
types.StructField('TEHBCombInnOonFamilyPerPersonMOOP', types.StringType()),
types.StructField('TEHBCombInnOonFamilyPerGroupMOOP', types.StringType()),
types.StructField('MEHBDedInnTier1Individual', types.StringType()),
types.StructField('MEHBDedInnTier1FamilyPerPerson', types.StringType()),
types.StructField('MEHBDedInnTier1FamilyPerGroup', types.StringType()),
types.StructField('MEHBDedInnTier1Coinsurance', types.StringType()),
types.StructField('MEHBDedInnTier2Individual', types.StringType()),
types.StructField('MEHBDedInnTier2FamilyPerPerson', types.StringType()),
types.StructField('MEHBDedInnTier2FamilyPerGroup', types.StringType()),
types.StructField('MEHBDedInnTier2Coinsurance', types.StringType()),
types.StructField('MEHBDedOutOfNetIndividual', types.StringType()),
types.StructField('MEHBDedOutOfNetFamilyPerPerson', types.StringType()),
types.StructField('MEHBDedOutOfNetFamilyPerGroup', types.StringType()),
types.StructField('MEHBDedCombInnOonIndividual', types.StringType()),
types.StructField('MEHBDedCombInnOonFamilyPerPerson', types.StringType()),
types.StructField('MEHBDedCombInnOonFamilyPerGroup', types.StringType()),
types.StructField('DEHBDedInnTier1Individual', types.StringType()),
types.StructField('DEHBDedInnTier1FamilyPerPerson', types.StringType()),
types.StructField('DEHBDedInnTier1FamilyPerGroup', types.StringType()),
types.StructField('DEHBDedInnTier1Coinsurance', types.StringType()),
types.StructField('DEHBDedInnTier2Individual', types.StringType()),
types.StructField('DEHBDedInnTier2FamilyPerPerson', types.StringType()),
types.StructField('DEHBDedInnTier2FamilyPerGroup', types.StringType()),
types.StructField('DEHBDedInnTier2Coinsurance', types.StringType()),
types.StructField('DEHBDedOutOfNetIndividual', types.StringType()),
types.StructField('DEHBDedOutOfNetFamilyPerPerson', types.StringType()),
types.StructField('DEHBDedOutOfNetFamilyPerGroup', types.StringType()),
types.StructField('DEHBDedCombInnOonIndividual', types.StringType()),
types.StructField('DEHBDedCombInnOonFamilyPerPerson', types.StringType()),
types.StructField('DEHBDedCombInnOonFamilyPerGroup', types.StringType()),
types.StructField('TEHBDedInnTier1Individual', types.StringType()),
types.StructField('TEHBDedInnTier1FamilyPerPerson', types.StringType()),
types.StructField('TEHBDedInnTier1FamilyPerGroup', types.StringType()),
types.StructField('TEHBDedInnTier1Coinsurance', types.StringType()),
types.StructField('TEHBDedInnTier2Individual', types.StringType()),
types.StructField('TEHBDedInnTier2FamilyPerPerson', types.StringType()),
types.StructField('TEHBDedInnTier2FamilyPerGroup', types.StringType()),
types.StructField('TEHBDedInnTier2Coinsurance', types.StringType()),
types.StructField('TEHBDedOutOfNetIndividual', types.StringType()),
types.StructField('TEHBDedOutOfNetFamilyPerPerson', types.StringType()),
types.StructField('TEHBDedOutOfNetFamilyPerGroup', types.StringType()),
types.StructField('TEHBDedCombInnOonIndividual', types.StringType()),
types.StructField('TEHBDedCombInnOonFamilyPerPerson', types.StringType()),
types.StructField('TEHBDedCombInnOonFamilyPerGroup', types.StringType()),
types.StructField('IsHSAEligible', types.StringType()),
types.StructField('HSAOrHRAEmployerContribution', types.StringType()),
types.StructField('HSAOrHRAEmployerContributionAmount', types.StringType()),
types.StructField('URLForSummaryofBenefitsCoverage', types.StringType()),
types.StructField('PlanBrochure', types.StringType()),
])



rates_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('VersionNum', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('IssuerId2', types.StringType()),
types.StructField('FederalTIN', types.StringType()),
types.StructField('RateEffectiveDate', types.StringType()),
types.StructField('RateExpirationDate', types.StringType()),
types.StructField('PlanId', types.StringType()),
types.StructField('RatingAreaId', types.StringType()),
types.StructField('Tobacco', types.StringType()),
types.StructField('Age', types.StringType()),
#should be converted to FloatType afterwards
types.StructField('IndividualRate', types.FloatType()),
types.StructField('IndividualTobaccoRate', types.FloatType()),
types.StructField('Couple', types.FloatType()),
types.StructField('PrimarySubscriberAndOneDependent', types.FloatType()),
types.StructField('PrimarySubscriberAndTwoDependents', types.FloatType()),
types.StructField('PrimarySubscriberAndThreeOrMoreDependents', types.FloatType()),
types.StructField('CoupleAndOneDependent', types.FloatType()),
types.StructField('CoupleAndTwoDependents', types.FloatType()),
types.StructField('CoupleAndThreeOrMoreDependents', types.FloatType()),
#should be converted to integertype afterwards
types.StructField('RowNumber', types.IntegerType()),
])

#for 2017-2020
new_rates_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('FederalTIN', types.StringType()),
types.StructField('RateEffectiveDate', types.StringType()),
types.StructField('RateExpirationDate', types.StringType()),
types.StructField('PlanId', types.StringType()),
types.StructField('RatingAreaId', types.StringType()),
types.StructField('Tobacco', types.StringType()),
types.StructField('Age', types.StringType()),
types.StructField('IndividualRate', types.FloatType()),
types.StructField('IndividualTobaccoRate', types.FloatType()),
types.StructField('Couple', types.FloatType()),
types.StructField('PrimarySubscriberAndOneDependent', types.FloatType()),
types.StructField('PrimarySubscriberAndTwoDependents', types.FloatType()),
types.StructField('PrimarySubscriberAndThreeOrMoreDependents', types.FloatType()),
types.StructField('CoupleAndOneDependent', types.FloatType()),
types.StructField('CoupleAndTwoDependents', types.FloatType()),
types.StructField('CoupleAndThreeOrMoreDependents', types.FloatType()),
])



updated_plan_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('MarketCoverage', types.StringType()),
types.StructField('DentalOnlyPlan', types.StringType()),
types.StructField('TIN', types.StringType()),
types.StructField('StandardComponentId', types.StringType()),
types.StructField('PlanMarketingName', types.StringType()),
types.StructField('HIOSProductId', types.StringType()),
types.StructField('HPID', types.StringType()),
types.StructField('NetworkId', types.StringType()),
types.StructField('ServiceAreaId', types.StringType()),
types.StructField('FormularyId', types.StringType()),
types.StructField('IsNewPlan', types.StringType()),
types.StructField('PlanType', types.StringType()),
types.StructField('MetalLevel', types.StringType()),
types.StructField('DiseaseManagementProgramsOffered', types.StringType()),
types.StructField('PlanVariantMarketingName', types.StringType()),
])



updated_benefits_schema = types.StructType([
types.StructField('BusinessYear', types.StringType()),
types.StructField('StateCode', types.StringType()),
types.StructField('IssuerId', types.StringType()),
types.StructField('SourceName', types.StringType()),
types.StructField('ImportDate', types.StringType()),
types.StructField('StandardComponentId', types.StringType()),
types.StructField('PlanId', types.StringType()),
types.StructField('BenefitName', types.StringType()),
types.StructField('CopayInnTier1', types.StringType()),
types.StructField('CopayInnTier2', types.StringType()),
types.StructField('CopayOutofNet', types.StringType()),
types.StructField('CoinsInnTier1', types.StringType()),
types.StructField('CoinsInnTier2', types.StringType()),
types.StructField('CoinsOutofNet', types.StringType()),
])


crosswalk_schema = types.StructType([
types.StructField('State', types.StringType()),
types.StructField('DentalPlan', types.StringType()),
types.StructField('Old_PlanID', types.StringType()),
types.StructField('Old_IssuerID', types.StringType()),
types.StructField('Old_MultistatePlan', types.StringType()),
types.StructField('Old_MetalLevel', types.StringType()),
types.StructField('Old_ChildAdultOnly', types.StringType()),
types.StructField('FIPSCode', types.StringType()),
types.StructField('ZipCode', types.StringType()),
types.StructField('CrosswalkLevel', types.StringType()),
types.StructField('ReasonForCrosswalk', types.StringType()),
types.StructField('New PlanID', types.StringType()),
types.StructField('New_IssuerID', types.StringType()),
types.StructField('New_MultistatePlan', types.StringType()),
types.StructField('New_MetalLevel', types.StringType()),
types.StructField('New_ChildAdultOnly', types.StringType()),
])

new_crosswalk_schema = types.StructType([
types.StructField('State', types.StringType()),
types.StructField('DentalPlan', types.StringType()),
types.StructField('Old_PlanID', types.StringType()),
types.StructField('Old_IssuerID', types.StringType()),
types.StructField('Old_MultistatePlan', types.StringType()),
types.StructField('Old_MetalLevel', types.StringType()),
types.StructField('Old_ChildAdultOnly', types.StringType()),
types.StructField('FIPSCode', types.StringType()),
types.StructField('ZipCode', types.StringType()),
types.StructField('CrosswalkLevel', types.StringType()),
types.StructField('ReasonForCrosswalk', types.StringType()),
types.StructField('New_PlanID', types.StringType()),
types.StructField('New_IssuerID', types.StringType()),
types.StructField('New_MultistatePlan', types.StringType()),
types.StructField('New_MetalLevel', types.StringType()),
types.StructField('New_ChildAdultOnly', types.StringType()),
types.StructField('BusinessYear', types.StringType()),
])